service: whatsapp-handler
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ap-south-1
  memorySize: 128
functions:
  hello:
    handler: handler.hello
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true